version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:github-actions)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:pip)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "npm"
    directory: "/front"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:npm)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/db"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-server)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/discord"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-server)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps:dockerfile-bot)"
    labels:
      - "dependencies"
      - "automated pr"
    assignees:
      - "ukwhatn"
    reviewers:
      - "ukwhatn"
