name: Sync Template
'on':
  workflow_dispatch: null
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if repository is a template
        id: is_template
        run: |
          IS_TEMPLATE=$(gh repo view --json isTemplate --jq '.isTemplate')
          echo "is_template=$IS_TEMPLATE" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: actions-template-sync
        if: steps.is_template.outputs.is_template == 'false'
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: ukwhatn/application-template
          upstream_branch: develop
          pr_labels: automated pr, sync-template